// Authoritative WinDjView Extended release version.
#pragma once

#define WINDJVIEW_VERSION_MAJOR 4
#define WINDJVIEW_VERSION_MINOR 3
#define WINDJVIEW_VERSION_PATCH 0
#define WINDJVIEW_VERSION_BUILD 0

#define WINDJVIEW_VERSION_FILEVERSION \
	WINDJVIEW_VERSION_MAJOR,WINDJVIEW_VERSION_MINOR,WINDJVIEW_VERSION_PATCH,WINDJVIEW_VERSION_BUILD

#define WINDJVIEW_VERSION_STRINGIFY_IMPL(value) #value
#define WINDJVIEW_VERSION_STRINGIFY(value) WINDJVIEW_VERSION_STRINGIFY_IMPL(value)
#define WINDJVIEW_VERSION_DOTTED WINDJVIEW_VERSION_MAJOR.WINDJVIEW_VERSION_MINOR.WINDJVIEW_VERSION_PATCH
#define WINDJVIEW_VERSION_STRING WINDJVIEW_VERSION_STRINGIFY(WINDJVIEW_VERSION_DOTTED)

#define WINDJVIEW_VERSION_WIDEN_IMPL(value) L##value
#define WINDJVIEW_VERSION_WIDEN(value) WINDJVIEW_VERSION_WIDEN_IMPL(value)
#define WINDJVIEW_VERSION_WSTRING WINDJVIEW_VERSION_WIDEN(WINDJVIEW_VERSION_STRING)
